# Generated by Django 5.2 on 2025-05-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_and_bond_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='interest_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('compound', 'Compound')], max_length=100),
        ),
    ]
